// Hover-glossary definitions for `<Term>`. Plain object, no framework
// imports — safe to use from both client and server components. Keep each
// entry to 1-2 tight, layman-first sentences; this is a tooltip, not a
// textbook. If you add a metric/label elsewhere in the app, add its entry
// here so <Term k="..."> has something to show.
export const glossary: Record<string, string> = {
  roic:
    "Return on Invested Capital — how many cents of yearly profit the business squeezes from each dollar tied up in it. Above ~12% is strong; below the WACC it's destroying value.",
  wacc:
    "Weighted Average Cost of Capital — the minimum annual return the business must earn to satisfy its lenders and shareholders. It's the bar ROIC has to clear for the business to be creating value.",
  capm:
    "Capital Asset Pricing Model — the formula behind our auto discount rate: risk-free rate (10-yr Treasury) plus the stock's beta times the extra return investors demand for holding stocks over bonds (5.5%).",
  cagr:
    "Compound Annual Growth Rate — the single steady yearly growth rate that would take a number from its starting value to its ending value over N years, smoothing out the bumps in between.",
  fcf:
    "Free Cash Flow — cash left over after the business pays for its own operations and equipment. It's what could be paid out to owners without shrinking the business.",
  ocf:
    "Operating Cash Flow — cash generated by the core business before any spending on equipment, investments, or financing. The rawest cash number before capex is subtracted.",
  ebitda:
    "Earnings before interest, tax, depreciation & amortization — profit before financing costs and non-cash accounting charges, often used to compare profitability across companies with different debt loads or asset ages.",
  ev:
    "Enterprise Value — what it would cost to buy the whole business: market cap plus debt, minus cash. It's the price tag for the operating business itself, independent of how it's financed.",
  pe:
    "Price/Earnings — the stock price divided by annual profit per share. Roughly, how many years of today's profit you're paying for one share.",
  peg:
    "PEG ratio — the P/E divided by the growth rate. A PEG near 1 suggests the price is roughly fair for how fast the company is growing; well above 1 suggests you're paying up for that growth.",
  beta:
    "Beta — how much a stock swings compared to the overall market. A beta of 1.5 means it tends to move about 50% more than the market, up or down.",
  grossMargin:
    "Gross margin — the % of each sales dollar left after covering the direct cost of making the product or service, before overhead, R&D, or marketing.",
  netMargin:
    "Net margin — the % of each sales dollar that turns into actual bottom-line profit after every expense, interest, and tax.",
  operatingMargin:
    "Operating margin — the % of each sales dollar left after running the core business (before interest and taxes) — a cleaner read on operating efficiency than net margin.",
  netDebt:
    "Net debt — total debt minus cash on hand. Negative net debt means the company holds more cash than it owes — a cushion rather than a burden.",
  buybackYield:
    "Buyback yield — shares repurchased over the past year as a % of market cap. Roughly the reverse of a dividend: cash returned to owners by shrinking the share count instead of paying cash out.",
  terminalGrowth:
    "Terminal growth — the steady, forever-after growth rate assumed once the company matures, pinned near long-run GDP growth (4% here) since no company can outgrow the economy indefinitely.",
  discountRate:
    "Discount rate — the annual % used to shrink future cash back to today's dollars, reflecting both the time value of money and the riskiness of the business. Same thing as WACC in our models.",
  trimmedMean:
    "Trimmed mean — an average that first throws out the single highest and lowest values, so one wildly optimistic or pessimistic estimate can't skew the result.",
  marketCap:
    "Market capitalization — the total value the stock market currently assigns to all of a company's shares (share price × shares outstanding).",
  eps:
    "Earnings per share — net income divided by shares outstanding: how much profit is attributable to each individual share.",
  dso:
    "Days Sales Outstanding — the average number of days it takes a company to collect cash after a sale. Lower is generally better (faster cash collection).",
  maintenanceCapex:
    "Maintenance capex — the portion of capital spending needed just to keep the existing business running (replacing worn-out equipment), as opposed to spending on growth. We estimate it as 60% of total capex.",
  ownerEarnings:
    "Owner earnings — Warren Buffett's cash-focused profit measure: net income plus depreciation, minus the maintenance capex needed to keep the business as-is. Meant to capture the cash an owner could actually pocket.",
  epv:
    "Earnings Power Value — what the business is worth today assuming zero future growth, just its current earning power capitalized at the discount rate. A skeptic's floor value, not an upside case.",
  impliedGrowth:
    "Implied growth — the growth rate you'd have to plug into our DCF for it to exactly reproduce today's market price. It's the growth the market is already betting on.",
  // Extra entries — not in the original glossary spec, but needed so the
  // Term wraps requested on these surfaces (Metrics page, SuperInvestor
  // stats, GateCard readings) have a real definition to show.
  spread:
    "Spread — ROIC minus WACC, in percentage points. Positive means the business earns more than its cost of capital (value-creating); negative means it's destroying value even while growing.",
  roe:
    "Return on Equity — annual profit as a % of shareholders' equity. Unlike ROIC, it ignores debt, so a heavily-indebted company can show an inflated ROE.",
  currentRatio:
    "Current ratio — current assets divided by current liabilities. Above 1 means the company can cover its near-term bills with what it already has on hand; well below 1 is a liquidity warning sign.",
  interestCoverage:
    "Interest coverage — operating income divided by interest expense: how many times over the company could pay its interest bill from operating profit alone. Lower means more strain from debt.",
  debtToEquity:
    "Debt/Equity — total debt divided by shareholders' equity. Higher means the company is financed more by borrowing than by owner capital, which amplifies both gains and losses.",
  ownerYield:
    "Owner-earnings yield — owner earnings divided by market cap, compared against the 10-year Treasury yield. A positive spread means the business's real cash profit beats what you'd earn risk-free.",
};
